import "dotenv/config";

const {
  PORT,
  MONGO_URI,
  JWT_SECRET,
  NODE_ENV,
  CLIENT_URL,
  RESEND_API_KEY,
  EMAIL_FROM,
  EMAIL_FROM_NAME,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  ARCJET_KEY,
  ARCJET_ENV,
} = process.env

export const ENV = {
  PORT,
  MONGO_URI,
  JWT_SECRET,
  NODE_ENV,
  CLIENT_URL,
  RESEND_API_KEY,
  EMAIL_FROM,
  EMAIL_FROM_NAME,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  ARCJET_KEY,
  ARCJET_ENV,
}
